name: Foobar

on:
  push:
    branches: ["*"]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "Full github context: ${GITHUB_CONTEXT}"
