name: Tag pushed to main

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    environment: staging
    if: contains(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test that building works with target and latest versions
        # of Python supported by App Engine
        python-version: [3.7, 3.10]
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Install poetry
        # pipx comes preinstalled
        run: pipx install poetry

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Poetry build
        run: poetry build

      - name: pypi-publish
        # only publish modules when bundled with version 3.7
        # since that is the target version of App Engine
        # probably would work either way though
        if: matrix.python-version == 3.7
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
