name: PR Checklist

on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        required: true
      repo:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Get list of files changed by this PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          processed=""
          while read -r line; do
              processed+="${line}__I__"
          done < <(gh api \
            -H "Accept: application/vnd.github+json" \
            --jq '.[] | .filename' \
            --paginate \
            /repos/${{ inputs.repo }}/pulls/${{ inputs.pr-number }}/files)
          echo "::debug::Processed ${processed::-5}"
          echo "FILES_CHANGED<<EOF" >> $GITHUB_ENV
          echo ${processed::-5} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Call PR Checklist
        id: pr-checklist
        uses: ./.github/actions/pr-checklist
        with:
          files-changed: ${{ env.FILES_CHANGED }}
          files-required: "^pyproject.toml$"
          files-optional: "^README.md$__I__^docs\\/.*__I__^CHANGELOG.md$"

      - name: Report results
        run: |
          missing=${{ steps.pr-checklist.outputs.missing }}
          skipped=${{ steps.pr-checklist.outputs.skipped }}
          found=${{ steps.pr-checklist.outputs.found }}
          echo "::debug::missing: $missing"
          echo "::debug::skipped: $skipped"
          echo "::debug::found: $found"
          echo "# PR Checklist" > pr_checklist_comment.md
          echo "" >> pr_checklist_comment.md
          function __printoutput() {
            filesin=$1
            emoji=$2
            phrase=$3
            arr=($(awk -F '__I__' '{
              for (i=0; ++i <= NF;)
                print $i
              }' <<< $filesin))
            for filename in "${arr[@]}"; do
              if [[ -z $filename ]]; then
                continue
              fi
              echo "- $emoji $phrase $filename" >> pr_checklist_comment.md
            done
          }
          __printoutput $missing ':x:' 'Missing'
          __printoutput $skipped ':eyes:' 'Skipped'
          __printoutput $found ':white_check_mark:' 'Found'
          if [[ -n $missing ]]; then
            echo "::error::Required files were not found."
            exit 1

      - name: Comment results
        if: ${{ always() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr_checklist_comment.md
