name: PR Checklist

on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        required: true
      repo:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Get list of files changed by this PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          filenames=$(gh api \
            -H "Accept: application/vnd.github+json" \
            --jq '.[] | .filename' \
            --paginate \
            /repos/${{ inputs.repo }}/pulls/${{ inputs.pr-number }}/files | sed 's/\n/__I__/g')
          echo 'FILES_CHANGED<<EOF' >> $GITHUB_ENV
          echo $filenames >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Call PR Checklist
        uses: ./.github/actions/pr-checklist
        with:
          files-changed: ${{ env.FILES_CHANGED }}
