name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Publish Ref ${{ github.event.ref }}"
