name: On Push to Feature Branch, run basic testing

on:
  push:
    branches: [ "feature/**" ]
  # manually trigger
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: echo Hello, world!
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo linting these files,
          echo linting those files
